### ISSUE TITLE
Empty snv.tsv and indel.tsv files

### ISSUE THREAD

**Issue by aditisk** [genome/docker-bam_readcount_helper-cwl#8]
Hello,

I'm using this helper function to prepare my input files for pVACtools. I don't see an error message but I'm pasting the output from my terminal below:

`[W::vcf_parse] Extreme INFO/MPOS value encountered and set to missing at chr1:999089
Complex variant or MNP will be skipped: chr1	1053478	CC	TT
Complex variant or MNP will be skipped: chr1	1084023	GG	AA
Complex variant or MNP will be skipped: chr1	1286134	CC	TT
Complex variant or MNP will be skipped: chr1	1374278	GG	AA
Complex variant or MNP will be skipped: chr1	1512446	AA	TT
Complex variant or MNP will be skipped: chr1	1599654	CA	TG
Complex variant or MNP will be skipped: chr1	3631025	TC	CT
Complex variant or MNP will be skipped: chr1	3631034	AG	GA
Complex variant or MNP will be skipped: chr1	6128865	CC	TT
Complex variant or MNP will be skipped: chr1	6208979	CA	TG
`

I am getting this same message for all the chromosomes. I checked my VCF file and I do have SNPs in the file. The 2 tsv files get created but are empty. Could you please advice on how to fix this ?

Thanks

**Comment by susannasiebert** [comment]
Can you please attach your input VCF for further debugging on our end?

**Comment by aditisk** [comment]
I am attaching a shortened version of my original VCF file here for debugging.

[example.vcf.zip](https://github.com/genome/docker-bam_readcount_helper-cwl/files/5168904/example.vcf.zip)

**Comment by aditisk** [comment]
Hi @susannasiebert, any updates on this ? Please let me know if you need anything else from me. Thank you.

**Comment by susannasiebert** [comment]
I apologize but I've been absolutely swamped with other projects. I will be on vacation this week but will look into it when I get back.

**Comment by aditisk** [comment]
Thanks for the update. Enjoy your time off :)

**Comment by susannasiebert** [comment]
I dug into this and from what I can tell it does generate region lists for the SNPs in your file (those files are tmp files so you won't see them as an output). If the final output files are empty, this usually means that those positions are low quality. You could try investigating these positions in IGV and/or adjusting the min_base_quality and and min_mapping_quality parameters.  Are you seeing this issue for both samples?

**Comment by aditisk** [comment]
Hi @susannasiebert, thanks for looking into this. I needed some clarification on your suggestion:

1. Which positions should I look at in IGV ? I don't see the region lists so I don't know what to focus on
2. At which step should I adjust the min_base_quality and and min_mapping_quality parameters ?

I tried this on multiple VCFs and I'm getting the same issue.

**Comment by susannasiebert** [comment]
1. I have attached the region lists for your VCF.
[region_files.zip](https://github.com/genome/docker-bam_readcount_helper-cwl/files/5312851/region_files.zip)

2. The `min_base_quality` and the `min_mapping_quality` are optional parameters to the `bam_readcount_helper.py` script (last two positional parameters, in that order). 

If you are having problems with all of your VCFs, that's indeed concerning. Without having access to your bams or the reference fasta you chose, I can't really debug it on my end. I would also need some more information on how precisely you are running things on your end.

**Comment by aditisk** [comment]
Thanks for sending these. I’ll do a little investigation on my end and get back to you by the end of the week. Thanks for your help.
